name: CI 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.2']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: npm install
    - run: npm run build
    - run: npm run test -- --coverage
    - run: npm run lint
    - run: npm run prettier

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Generate code coverage badge
      uses: badgen/badgen-action@v1
      with:
        subject: 'coverage'
        status: ${{ env.CODECOV_REPORTER }}%
        color: ${{ env.CODECOV_REPORTER >= 80 && 'brightgreen' || env.CODECOV_REPORTER >= 60 && 'yellow' || 'red' }}
        icon: 'codecov'
        label: 'coverage'
