name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.2']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: npm install
    - run: npm run build
    - run: npm run test
    - run: npm run lint
    - run: npm run prettier


- name: Generate CI status badge
  uses: badgen/badgen-action@v1
  with:
    subject: 'CI'
    status: ${{ job.status }}
    color: ${{ job.status == 'success' && 'green' || 'red' }}
    icon: 'github'
    label: 'status'

- name: Generate code coverage badge
  uses: badgen/badgen-action@v1
  with:
    subject: 'coverage'
    status: ${{ env.CODECOV_REPORTER }}%
    color: ${{ env.CODECOV_REPORTER >= 80 && 'brightgreen' || env.CODECOV_REPORTER >= 60 && 'yellow' || 'red' }}
    icon: 'codecov'
    label: 'coverage'